### ISSUE TITLE
英文下按钮文案修改

### ISSUE THREAD

**Issue by jianfei** [uxcore/uxcore-dialog#16]
Dialog.xxx现在的用是ok和cancel。建议改成OK（或Okay）和Cancel
建议Dialog.confirm改成Yes，因为用confirm一般上面会用Are you sure you want to....，用Yes比OK更准确。

**Comment by eternalsky** [comment]
fix in  https://github.com/uxcore/uxcore-dialog/commit/e98ca1df5694ac52b1324a0afc14e6ceb5c00e58
