### ISSUE TITLE
Dialog.info(success,error,confirm) 希望能自定义按钮的文字内容

### ISSUE THREAD

**Issue by youngBrain1893** [uxcore/uxcore-dialog#18]
设计上是希望就展示那几个文字内容，实际产品场景中经常遇到要求个性化定制文案，而且这几个快捷方法又不支持 `footer` 参数，使用起来就比较麻烦了

**Comment by eternalsky** [comment]
设计初衷是为了简化操作，少传一些东西进去，不过目前有很多类似需求，这周可以搞一下。
