### ISSUE TITLE
当前的css样式，对自定义header背景颜色不友好

### ISSUE THREAD

**Issue by paseo** [uxcore/uxcore-dialog#24]
当前的css样式层级下，如果需要设置header的背景色，当前kuma-dlg-header和kuma-dlg-title的样式设置方式让自定义header背景色变得困难。

对比了ant.design，相同的html结构下，对方的Modal组件在自定义header背景色时就非常方便。

**Comment by eternalsky** [comment]
我的理解，你的意思应该是因为现在是 title 设置 margin 做的布局，所以修改 header 的 background，并不是你想要的效果？需要再同时设置一下 title 的样式，是这样吗？

**Comment by xingmolu** [comment]
f180a84 fixed
