### ISSUE TITLE
组件库现在还不支持react16版本吗？

### ISSUE THREAD

**Issue by jonyshi** [uxcore/uxcore-dialog#25]
组件库现在还不支持react16版本吗？在react16.0中使用报错？怎么办？

**Comment by eternalsky** [comment]
恩，目前还只适配到 React@15.x

**Comment by jonyshi** [comment]
后续有准备做升级处理吗？

**Comment by eternalsky** [comment]
后续会有，但近期可能暂时不会。不过如果有 React@16.x 相应的报错，也可以提 issue，我们会针对性地进行修改适配。

**Comment by albertbee** [comment]
已经支持react16
