### ISSUE TITLE
加时间，点击知道了就报错

### ISSUE THREAD

**Issue by shiqiwodezuiai** [uxcore/uxcore-dialog#31]
Dialog.success({
      title: title,
      content: <span>{tishi[0]}，{tishi[1]}<a href="http://www.baidu.com">{i18n["btn.confirm-msg"]}</a>{tishi[2]}</span>,
      timer: 5000,
    });
加了timer,点击知道了报以下错误：
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**Comment by albertbee** [comment]
This error does't break the script, only show error in console, because the element has been removed by handle, when the timer is done, close function try to remove the element, the element did not in the body ever.
